# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('measurements', models.ManyToManyField(to='berryface.MeasureType')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berryface.SensorType'),
        ),
        migrations.AddField(
            model_name='entry',
            name='measure_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berryface.MeasureType'),
        ),
        migrations.AddField(
            model_name='entry',
            name='sensor_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berryface.SensorType'),
        ),
    ]
