# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berryface', '0005_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=400)),
                ('token', models.CharField(max_length=100)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berryface.Role')),
            ],
        ),
    ]
