# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berryface', '0006_role_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='Jessica', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='Wong', max_length=250),
            preserve_default=False,
        ),
    ]
