# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berryface', '0007_auto_20180619_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_date',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
